# SPDX-FileCopyrightText: 2025 Alexandru Mihai Buzduc <lalibuzduc@gmail,com>
# SPDX-License-Identifier: FSFAP
#
# Copyright 2025, Alexandru Mihai Buzduc <lalibuzduc@gmail.com>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-domain: "mymetype.nekoweb.org"
          nekoweb-username: "MymeType"
          directory: "src"
